### PR TITLE
Add coloring for group, groupdesc, option, optiondesc

### PR DESCRIPTION
**Pull request by rrthomas**

### CODE REVIEW

**Comment by rrthomas** [comment]
Not sure if I've missed something, since the mode clearly knows about these keywords, but surely they should be colored in the same way as `section` and `sectiondesc`?

**Comment by mkjunker** [comment]
Agree.  Merged to master.

**Comment by rrthomas** [comment]
Thanks! Please could we have a tag/release (for MELPA stable)?

**Comment by mkjunker** [comment]
Thanks for reminding me.  It's long time since I worked in MELPA.  The update is in MELPA stable.

**Comment by rrthomas** [comment]
Many thanks!

**Comment by mkjunker** [comment]
I'm having problems with the stable version not showing up in the package list, perhaps related to the time not being in the version string.  Let me know if you have any problems.

**Comment by rrthomas** [comment]
It's showing up for me!

**Pull request merged**
